title: Binit Kumar
description: >
    My description
    <br><br>
    <a href="your_website">website</a>
email: 'kumar.binit1992@gmail.com'


navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
  

description: "I'm a software and data engineer from Montreal creating useful apps."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://binit92.github.io" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: 'binit92'
github_username: 'binit92'
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal


social-network-links:
  email: "someone@example.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali


gems:
  - jekyll-mentions
