title: Binit Kumar

description: "I'm a software and data engineer from Montreal creating useful apps."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://binit92.github.io" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: 'binit92'
github_username: 'binit92'
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal




# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)



# Site Author
author:
  name             : "Your Name"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : "Montreal"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kumar.binit1992@gmail.com"
    - label: "Resume"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/binit92/resume/raw/master/pdf/resume_Binit_Kumar.pdf"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/binit92"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/binit92"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/_binitkumar/"



gems:
  - jekyll-mentions
